export const BUSINESS_DAYS = [
  "Lunes",
  "Martes",
  "Miercoles",
  "Jueves",
  "Viernes",
  "Sabado",
  "Domingo",
] as const;

export const BUSINESS_HOURS = BUSINESS_DAYS.reduce<Record<string, { start: string; end: string }[]>>(
  (acc, day) => {
    acc[day === "Miercoles" ? "Miércoles" : day === "Sabado" ? "Sábado" : day] = [
      { start: "19:00", end: "23:30" },
    ];
    return acc;
  },
  {}
);

export const APP_CONFIGS = {
  "business.profile": {
    name: "La Trattoria",
    address: "Av. Principal 123",
    logo: "",
  },
  "business.hours": BUSINESS_HOURS,
  "business.closedDays": [],
  "payments.methods": [
    { id: "EFECTIVO", label: "Efectivo", enabled: true, sortOrder: 0 },
    { id: "TRANSFERENCIA", label: "Transferencia", enabled: true, sortOrder: 1 },
    { id: "MERCADOPAGO", label: "Mercado Pago", enabled: false, sortOrder: 2 },
  ],
  "integrations.mercadoPago": {
    publicKey: "",
    enabled: false,
  },
  "delivery.settings": {
    enabled: true,
    deliveryFeeNear: 1500,
    deliveryFeeFar: 2500,
    estimatedTimeRange: "30-45 min",
    allowPickup: true,
    allowDelivery: true,
  },
  "whatsapp.settings": {
    phoneNumber: "5491112345678",
    templateMessage:
      "Hola {nombre}! Gracias por elegir La Trattoria.\n\nRecibimos tu pedido #{id} correctamente.\n\n- Entrega en: {direccion}\n- Total: {total}\n- Metodo de pago: {metodoPago}\n\nDetalle:\n{items}\n\nEstamos preparando tu pedido.\n\n- Tipo de entrega: {tipoEntrega}\n- Telefono: {telefono}",
    enabled: true,
  },
  "goals.monthly": {
    amount: 2500000,
    type: "revenue",
  },
} as const;

export const APP_SEQUENCES = [
  { tipo: "order", prefijo: "ORD-", ultimo: 0 },
  { tipo: "egreso", prefijo: "E-", ultimo: 0 },
] as const;

export const CATEGORY_SEEDS = [
  {
    slug: "pizzas",
    nombre: "Pizzas",
    descripcion: "Pizzas artesanales al molde.",
    orden: 0,
    esPromocion: false,
  },
  {
    slug: "pastas",
    nombre: "Pastas",
    descripcion: "Pastas caseras con salsas clasicas.",
    orden: 1,
    esPromocion: false,
  },
  {
    slug: "empanadas",
    nombre: "Empanadas",
    descripcion: "Empanadas artesanales de la casa.",
    orden: 2,
    esPromocion: false,
  },
  {
    slug: "milanesas",
    nombre: "Milanesas",
    descripcion: "Milanesas con opciones clasicas y napolitanas.",
    orden: 3,
    esPromocion: false,
  },
  {
    slug: "hamburguesas",
    nombre: "Hamburguesas",
    descripcion: "Hamburguesas caseras con pan artesanal.",
    orden: 4,
    esPromocion: false,
  },
  {
    slug: "postres",
    nombre: "Postres",
    descripcion: "Postres clasicos para cerrar la comida.",
    orden: 5,
    esPromocion: false,
  },
  {
    slug: "bebidas",
    nombre: "Bebidas",
    descripcion: "Bebidas frias para acompanar tu pedido.",
    orden: 6,
    esPromocion: false,
  },
  {
    slug: "promos",
    nombre: "Promos",
    descripcion: "Combos promocionales listos para vender.",
    orden: 7,
    esPromocion: true,
  },
] as const;

export const SUPPLY_SEEDS = [
  { nombre: "Harina de trigo", categoria: "Secos", unidad: "KILOGRAMO", stockMinimo: 20, costoUnitario: 1200 },
  { nombre: "Salsa de tomate", categoria: "Salsas", unidad: "KILOGRAMO", stockMinimo: 10, costoUnitario: 1800 },
  { nombre: "Queso mozzarella", categoria: "Lacteos", unidad: "KILOGRAMO", stockMinimo: 8, costoUnitario: 8200 },
  { nombre: "Queso parmesano", categoria: "Lacteos", unidad: "KILOGRAMO", stockMinimo: 2, costoUnitario: 17000 },
  { nombre: "Queso roquefort", categoria: "Lacteos", unidad: "KILOGRAMO", stockMinimo: 2, costoUnitario: 14500 },
  { nombre: "Queso crema", categoria: "Lacteos", unidad: "KILOGRAMO", stockMinimo: 2, costoUnitario: 7600 },
  { nombre: "Jamon cocido", categoria: "Fiambres", unidad: "KILOGRAMO", stockMinimo: 4, costoUnitario: 9800 },
  { nombre: "Calabresa", categoria: "Fiambres", unidad: "KILOGRAMO", stockMinimo: 3, costoUnitario: 10500 },
  { nombre: "Carne picada", categoria: "Carnes", unidad: "KILOGRAMO", stockMinimo: 6, costoUnitario: 9000 },
  { nombre: "Pechuga de pollo", categoria: "Carnes", unidad: "KILOGRAMO", stockMinimo: 5, costoUnitario: 7200 },
  { nombre: "Nalga para milanesa", categoria: "Carnes", unidad: "KILOGRAMO", stockMinimo: 5, costoUnitario: 11200 },
  { nombre: "Pan de hamburguesa", categoria: "Panificados", unidad: "UNIDAD", stockMinimo: 24, costoUnitario: 420 },
  { nombre: "Tomate fresco", categoria: "Verduras", unidad: "KILOGRAMO", stockMinimo: 8, costoUnitario: 1600 },
  { nombre: "Cebolla", categoria: "Verduras", unidad: "KILOGRAMO", stockMinimo: 8, costoUnitario: 1100 },
  { nombre: "Morron", categoria: "Verduras", unidad: "KILOGRAMO", stockMinimo: 4, costoUnitario: 2600 },
  { nombre: "Aceitunas", categoria: "Verduras", unidad: "KILOGRAMO", stockMinimo: 2, costoUnitario: 6500 },
  { nombre: "Oregano", categoria: "Condimentos", unidad: "GRAMO", stockMinimo: 200, costoUnitario: 35 },
  { nombre: "Albahaca", categoria: "Verduras", unidad: "GRAMO", stockMinimo: 120, costoUnitario: 28 },
  { nombre: "Champinones", categoria: "Verduras", unidad: "KILOGRAMO", stockMinimo: 2, costoUnitario: 9800 },
  { nombre: "Huevo", categoria: "Huevos", unidad: "UNIDAD", stockMinimo: 60, costoUnitario: 260 },
  { nombre: "Papa", categoria: "Verduras", unidad: "KILOGRAMO", stockMinimo: 8, costoUnitario: 950 },
  { nombre: "Panko", categoria: "Secos", unidad: "KILOGRAMO", stockMinimo: 4, costoUnitario: 2100 },
  { nombre: "Lechuga", categoria: "Verduras", unidad: "UNIDAD", stockMinimo: 10, costoUnitario: 380 },
  { nombre: "Queso cheddar", categoria: "Lacteos", unidad: "KILOGRAMO", stockMinimo: 3, costoUnitario: 9200 },
  { nombre: "Papas prefritas", categoria: "Congelados", unidad: "KILOGRAMO", stockMinimo: 6, costoUnitario: 3200 },
  { nombre: "Cafe", categoria: "Secos", unidad: "KILOGRAMO", stockMinimo: 1, costoUnitario: 16000 },
  { nombre: "Azucar", categoria: "Secos", unidad: "KILOGRAMO", stockMinimo: 6, costoUnitario: 1300 },
  { nombre: "Cacao", categoria: "Secos", unidad: "KILOGRAMO", stockMinimo: 2, costoUnitario: 8600 },
  { nombre: "Leche", categoria: "Lacteos", unidad: "LITRO", stockMinimo: 10, costoUnitario: 1500 },
  { nombre: "Crema", categoria: "Lacteos", unidad: "LITRO", stockMinimo: 4, costoUnitario: 2200 },
  { nombre: "Dulce de leche", categoria: "Dulces", unidad: "KILOGRAMO", stockMinimo: 3, costoUnitario: 5400 },
  { nombre: "Tapas de empanada", categoria: "Panificados", unidad: "UNIDAD", stockMinimo: 100, costoUnitario: 120 },
  { nombre: "Agua mineral 500ml", categoria: "Bebidas", unidad: "UNIDAD", stockMinimo: 24, costoUnitario: 550 },
  { nombre: "Coca Cola 1.5L", categoria: "Bebidas", unidad: "UNIDAD", stockMinimo: 12, costoUnitario: 1650 },
  { nombre: "Cerveza lager 1L", categoria: "Bebidas", unidad: "UNIDAD", stockMinimo: 12, costoUnitario: 2100 },
] as const;

export const PROVIDER_SEEDS = [
  { nombre: "Lacteos del Centro", contacto: "Martin Perez", direccion: "Mercado Central 245", email: "ventas@lacteoscentro.test" },
  { nombre: "Carnes del Mercado", contacto: "Laura Gomez", direccion: "Av. Mataderos 810", email: "pedidos@carnesmercado.test" },
  { nombre: "Verduleria del Barrio", contacto: "Sofia Diaz", direccion: "Calle 8 1142", email: "contacto@verduleriadelbarrio.test" },
  { nombre: "Distribuidora Sur", contacto: "Diego Rios", direccion: "Ruta 4 km 12", email: "ventas@distribuidorasur.test" },
] as const;

export const PRODUCT_SEEDS = [
  {
    nombre: "Pizza Muzzarella",
    descripcion: "Salsa de tomate, mozzarella, oregano y aceitunas.",
    precio: 9800,
    costoUnitario: 4200,
    categorySlug: "pizzas",
    orden: 0,
    recipe: [
      { supplyName: "Harina de trigo", qtyPerUnit: 0.32, unidad: "KILOGRAMO" },
      { supplyName: "Salsa de tomate", qtyPerUnit: 0.18, unidad: "KILOGRAMO" },
      { supplyName: "Queso mozzarella", qtyPerUnit: 0.28, unidad: "KILOGRAMO" },
      { supplyName: "Aceitunas", qtyPerUnit: 0.03, unidad: "KILOGRAMO" },
      { supplyName: "Oregano", qtyPerUnit: 8, unidad: "GRAMO" },
    ],
  },
  {
    nombre: "Pizza Napolitana",
    descripcion: "Mozzarella, tomate fresco, ajo y oregano.",
    precio: 10800,
    costoUnitario: 4700,
    categorySlug: "pizzas",
    orden: 1,
    recipe: [
      { supplyName: "Harina de trigo", qtyPerUnit: 0.32, unidad: "KILOGRAMO" },
      { supplyName: "Salsa de tomate", qtyPerUnit: 0.18, unidad: "KILOGRAMO" },
      { supplyName: "Queso mozzarella", qtyPerUnit: 0.27, unidad: "KILOGRAMO" },
      { supplyName: "Tomate fresco", qtyPerUnit: 0.12, unidad: "KILOGRAMO" },
      { supplyName: "Oregano", qtyPerUnit: 8, unidad: "GRAMO" },
    ],
  },
  {
    nombre: "Pizza Fugazzeta",
    descripcion: "Mozzarella, cebolla y aceitunas.",
    precio: 11200,
    costoUnitario: 4900,
    categorySlug: "pizzas",
    orden: 2,
    recipe: [
      { supplyName: "Harina de trigo", qtyPerUnit: 0.32, unidad: "KILOGRAMO" },
      { supplyName: "Queso mozzarella", qtyPerUnit: 0.29, unidad: "KILOGRAMO" },
      { supplyName: "Cebolla", qtyPerUnit: 0.18, unidad: "KILOGRAMO" },
      { supplyName: "Aceitunas", qtyPerUnit: 0.03, unidad: "KILOGRAMO" },
      { supplyName: "Oregano", qtyPerUnit: 8, unidad: "GRAMO" },
    ],
  },
  {
    nombre: "Pizza Calabresa",
    descripcion: "Mozzarella, calabresa y morron.",
    precio: 11800,
    costoUnitario: 5300,
    categorySlug: "pizzas",
    orden: 3,
    recipe: [
      { supplyName: "Harina de trigo", qtyPerUnit: 0.32, unidad: "KILOGRAMO" },
      { supplyName: "Salsa de tomate", qtyPerUnit: 0.18, unidad: "KILOGRAMO" },
      { supplyName: "Queso mozzarella", qtyPerUnit: 0.26, unidad: "KILOGRAMO" },
      { supplyName: "Calabresa", qtyPerUnit: 0.12, unidad: "KILOGRAMO" },
      { supplyName: "Morron", qtyPerUnit: 0.05, unidad: "KILOGRAMO" },
    ],
  },
  {
    nombre: "Ravioles con Fileto",
    descripcion: "Ravioles de la casa con salsa fileto y parmesano.",
    precio: 9200,
    costoUnitario: 3900,
    categorySlug: "pastas",
    orden: 0,
    recipe: [
      { supplyName: "Harina de trigo", qtyPerUnit: 0.18, unidad: "KILOGRAMO" },
      { supplyName: "Salsa de tomate", qtyPerUnit: 0.16, unidad: "KILOGRAMO" },
      { supplyName: "Queso parmesano", qtyPerUnit: 0.02, unidad: "KILOGRAMO" },
      { supplyName: "Huevo", qtyPerUnit: 2, unidad: "UNIDAD" },
    ],
  },
  {
    nombre: "Nhoquis Bolognesa",
    descripcion: "Nhoquis caseros con salsa bolognesa.",
    precio: 9500,
    costoUnitario: 4100,
    categorySlug: "pastas",
    orden: 1,
    recipe: [
      { supplyName: "Papa", qtyPerUnit: 0.35, unidad: "KILOGRAMO" },
      { supplyName: "Harina de trigo", qtyPerUnit: 0.08, unidad: "KILOGRAMO" },
      { supplyName: "Carne picada", qtyPerUnit: 0.12, unidad: "KILOGRAMO" },
      { supplyName: "Salsa de tomate", qtyPerUnit: 0.18, unidad: "KILOGRAMO" },
    ],
  },
  {
    nombre: "Empanada de Carne",
    descripcion: "Empanada clasica de carne cortada a cuchillo.",
    precio: 1500,
    costoUnitario: 620,
    categorySlug: "empanadas",
    orden: 0,
    recipe: [
      { supplyName: "Tapas de empanada", qtyPerUnit: 1, unidad: "UNIDAD" },
      { supplyName: "Carne picada", qtyPerUnit: 0.08, unidad: "KILOGRAMO" },
      { supplyName: "Cebolla", qtyPerUnit: 0.02, unidad: "KILOGRAMO" },
      { supplyName: "Huevo", qtyPerUnit: 0.25, unidad: "UNIDAD" },
    ],
  },
  {
    nombre: "Empanada de Jamon y Queso",
    descripcion: "Empanada de jamon cocido y mozzarella.",
    precio: 1450,
    costoUnitario: 590,
    categorySlug: "empanadas",
    orden: 1,
    recipe: [
      { supplyName: "Tapas de empanada", qtyPerUnit: 1, unidad: "UNIDAD" },
      { supplyName: "Jamon cocido", qtyPerUnit: 0.04, unidad: "KILOGRAMO" },
      { supplyName: "Queso mozzarella", qtyPerUnit: 0.04, unidad: "KILOGRAMO" },
    ],
  },
  {
    nombre: "Empanada de Pollo",
    descripcion: "Empanada de pollo con cebolla y morron.",
    precio: 1450,
    costoUnitario: 610,
    categorySlug: "empanadas",
    orden: 2,
    recipe: [
      { supplyName: "Tapas de empanada", qtyPerUnit: 1, unidad: "UNIDAD" },
      { supplyName: "Pechuga de pollo", qtyPerUnit: 0.07, unidad: "KILOGRAMO" },
      { supplyName: "Cebolla", qtyPerUnit: 0.02, unidad: "KILOGRAMO" },
      { supplyName: "Morron", qtyPerUnit: 0.01, unidad: "KILOGRAMO" },
    ],
  },
  {
    nombre: "Milanesa Clasica",
    descripcion: "Milanesa con guarnicion de papas.",
    precio: 11800,
    costoUnitario: 5400,
    categorySlug: "milanesas",
    orden: 0,
    recipe: [
      { supplyName: "Nalga para milanesa", qtyPerUnit: 0.28, unidad: "KILOGRAMO" },
      { supplyName: "Huevo", qtyPerUnit: 1, unidad: "UNIDAD" },
      { supplyName: "Panko", qtyPerUnit: 0.06, unidad: "KILOGRAMO" },
      { supplyName: "Papas prefritas", qtyPerUnit: 0.2, unidad: "KILOGRAMO" },
    ],
  },
  {
    nombre: "Milanesa Napolitana",
    descripcion: "Milanesa con salsa, jamon y mozzarella.",
    precio: 13200,
    costoUnitario: 6100,
    categorySlug: "milanesas",
    orden: 1,
    recipe: [
      { supplyName: "Nalga para milanesa", qtyPerUnit: 0.28, unidad: "KILOGRAMO" },
      { supplyName: "Huevo", qtyPerUnit: 1, unidad: "UNIDAD" },
      { supplyName: "Panko", qtyPerUnit: 0.06, unidad: "KILOGRAMO" },
      { supplyName: "Salsa de tomate", qtyPerUnit: 0.09, unidad: "KILOGRAMO" },
      { supplyName: "Jamon cocido", qtyPerUnit: 0.05, unidad: "KILOGRAMO" },
      { supplyName: "Queso mozzarella", qtyPerUnit: 0.08, unidad: "KILOGRAMO" },
    ],
  },
  {
    nombre: "Hamburguesa Clasica",
    descripcion: "Medallon casero con lechuga, tomate y papas.",
    precio: 9800,
    costoUnitario: 4300,
    categorySlug: "hamburguesas",
    orden: 0,
    recipe: [
      { supplyName: "Carne picada", qtyPerUnit: 0.16, unidad: "KILOGRAMO" },
      { supplyName: "Pan de hamburguesa", qtyPerUnit: 1, unidad: "UNIDAD" },
      { supplyName: "Lechuga", qtyPerUnit: 0.25, unidad: "UNIDAD" },
      { supplyName: "Tomate fresco", qtyPerUnit: 0.04, unidad: "KILOGRAMO" },
      { supplyName: "Papas prefritas", qtyPerUnit: 0.18, unidad: "KILOGRAMO" },
    ],
  },
  {
    nombre: "Hamburguesa Doble Queso",
    descripcion: "Doble medallon con cheddar y papas.",
    precio: 11800,
    costoUnitario: 5300,
    categorySlug: "hamburguesas",
    orden: 1,
    recipe: [
      { supplyName: "Carne picada", qtyPerUnit: 0.28, unidad: "KILOGRAMO" },
      { supplyName: "Pan de hamburguesa", qtyPerUnit: 1, unidad: "UNIDAD" },
      { supplyName: "Queso cheddar", qtyPerUnit: 0.06, unidad: "KILOGRAMO" },
      { supplyName: "Papas prefritas", qtyPerUnit: 0.18, unidad: "KILOGRAMO" },
    ],
  },
  {
    nombre: "Tiramisu",
    descripcion: "Postre italiano con cafe, crema y cacao.",
    precio: 5200,
    costoUnitario: 2100,
    categorySlug: "postres",
    orden: 0,
    recipe: [
      { supplyName: "Queso crema", qtyPerUnit: 0.08, unidad: "KILOGRAMO" },
      { supplyName: "Cafe", qtyPerUnit: 0.01, unidad: "KILOGRAMO" },
      { supplyName: "Azucar", qtyPerUnit: 0.02, unidad: "KILOGRAMO" },
      { supplyName: "Cacao", qtyPerUnit: 0.01, unidad: "KILOGRAMO" },
      { supplyName: "Huevo", qtyPerUnit: 1, unidad: "UNIDAD" },
    ],
  },
  {
    nombre: "Flan Casero",
    descripcion: "Flan con dulce de leche y crema.",
    precio: 4300,
    costoUnitario: 1700,
    categorySlug: "postres",
    orden: 1,
    recipe: [
      { supplyName: "Leche", qtyPerUnit: 0.18, unidad: "LITRO" },
      { supplyName: "Huevo", qtyPerUnit: 2, unidad: "UNIDAD" },
      { supplyName: "Azucar", qtyPerUnit: 0.03, unidad: "KILOGRAMO" },
      { supplyName: "Dulce de leche", qtyPerUnit: 0.03, unidad: "KILOGRAMO" },
      { supplyName: "Crema", qtyPerUnit: 0.03, unidad: "LITRO" },
    ],
  },
  {
    nombre: "Coca Cola 1.5L",
    descripcion: "Botella retornable de 1.5 litros.",
    precio: 3200,
    costoUnitario: 1650,
    categorySlug: "bebidas",
    orden: 0,
    recipe: [{ supplyName: "Coca Cola 1.5L", qtyPerUnit: 1, unidad: "UNIDAD" }],
  },
  {
    nombre: "Agua Mineral 500ml",
    descripcion: "Botella individual de agua sin gas.",
    precio: 1800,
    costoUnitario: 550,
    categorySlug: "bebidas",
    orden: 1,
    recipe: [{ supplyName: "Agua mineral 500ml", qtyPerUnit: 1, unidad: "UNIDAD" }],
  },
  {
    nombre: "Cerveza Lager 1L",
    descripcion: "Cerveza rubia de litro.",
    precio: 3900,
    costoUnitario: 2100,
    categorySlug: "bebidas",
    orden: 2,
    recipe: [{ supplyName: "Cerveza lager 1L", qtyPerUnit: 1, unidad: "UNIDAD" }],
  },
] as const;

export const PROMOTION_SEEDS = [
  {
    name: "Combo Pizza y Gaseosa",
    description: "Una pizza muzzarella con una Coca Cola 1.5L.",
    code: "PIZZA-GASEOSA",
    discountType: "FIXED_AMOUNT",
    discountValue: 1400,
    categorySlug: "promos",
    items: [
      { productName: "Pizza Muzzarella", quantity: 1 },
      { productName: "Coca Cola 1.5L", quantity: 1 },
    ],
  },
  {
    name: "Docena Mixta de Empanadas",
    description: "Empanadas surtidas para compartir.",
    code: "DOCENA-EMPANADAS",
    discountType: "FIXED_AMOUNT",
    discountValue: 1800,
    categorySlug: "promos",
    items: [
      { productName: "Empanada de Carne", quantity: 4 },
      { productName: "Empanada de Jamon y Queso", quantity: 4 },
      { productName: "Empanada de Pollo", quantity: 4 },
    ],
  },
  {
    name: "Burger Night",
    description: "Dos hamburguesas clasicas con cerveza lager.",
    code: "BURGER-NIGHT",
    discountType: "PERCENTAGE",
    discountValue: 12,
    categorySlug: "promos",
    items: [
      { productName: "Hamburguesa Clasica", quantity: 2 },
      { productName: "Cerveza Lager 1L", quantity: 1 },
    ],
  },
] as const;
